{
 "title": "Kubernetes Deployment CPU and Memory Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_deployment_status_condition,namespace)"
    }
   },
   {
    "name": "deployment",
    "query": {
     "query": "label_values(kube_deployment_status_condition{namespace=\"$namespace\"},deployment)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\", pod=~\"$deployment.*\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU and Memory Usage Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Deployment CPU Usage",
   "type": "timeseries",
   "description": "All pods CPU usage combined for selected deployment",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\", pod=~\"$deployment.*\"}) by (deployment)",
     "legendFormat": "$deployment - limit"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", pod=~\"$deployment.*\"}) by (deployment)",
     "legendFormat": "$deployment  - request"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$deployment.*\"}[$__rate_interval])) by (deployment)",
     "legendFormat": "$deployment  - usage"
    }
   ]
  },
  {
   "title": "Deployment Memory Usage",
   "type": "timeseries",
   "description": "All pods memory usage combined for selected deployment",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", pod=~\"$deployment.*\"}) by (deployment)",
     "legendFormat": "$deployment - limit"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\", pod=~\"$deployment.*\"}) by (deployment)",
     "legendFormat": "$deployment  - request"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"$deployment.*\"}) by (deployment)",
     "legendFormat": "$deployment  - usage"
    }
   ]
  },
  {
   "title": "CPU Request per Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", pod=~\"$deployment.*\"}) by (deployment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Limit per Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\", pod=~\"$deployment.*\"}) by (deployment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Request per Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\", pod=~\"$deployment.*\"}) by (deployment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Limit per Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", pod=~\"$deployment.*\"}) by (deployment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Resource Usage - $pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "repeat": "pod",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "All pods CPU usage combined for selected deployment",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\", pod=~\"$pod.*\"}) by (pod)",
       "legendFormat": "$pod - limit"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", pod=~\"$pod.*\"}) by (pod)",
       "legendFormat": "$pod  - request"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod.*\"}[$__rate_interval])) by (pod)",
       "legendFormat": "$pod  - usage"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "description": "All pods memory usage combined for selected deployment",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", pod=~\"$pod.*\"}) by (pod)",
       "legendFormat": "$pod - limit"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\", pod=~\"$pod.*\"}) by (pod)",
       "legendFormat": "$pod  - request"
      },
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"$pod.*\"}) by (pod)",
       "legendFormat": "$pod  - usage"
      }
     ]
    }
   ]
  }
 ]
}